linters:
  disable-all: true
  enable:
    - gofumpt
    - govet
#    - gci
    - staticcheck

issues:
  exclude-dirs:
    - internal

linters-settings:
#  gci:
#    sections:
#      - standard
#      - prefix(github.com/sagernet/sing)
#      - default
  staticcheck:
    go: '1.19'
